fernetKey: QmkyVmhqMnhDWElsNk5QcGJwVEsxY09PYkhvaFlsbEQ=
webserverSecretKey: QmkyVmhqMnhDWElsNk5QcGJwVEsxY09PYkhvaFlsbEQ=

dags:
  gitSync:
    enabled: true
    repo: https://github.com/arvindaggmca/Kubernetes-For-DataEngineering.git
    branch: main
    rev: HEAD
    depth: 1
    maxFailures: 0
    subPath: "dags"
